name: CI Pipeline
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Continious Integration
    steps:
    - uses: actions/checkout@v2    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build web api
      run: dotnet build --no-restore
      
    - name: Unit test
      run: dotnet test --no-build --verbosity normal
      
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.5
      with:
       args: -Dsonar.projectKey=kjetil-demo-api -Dsonar.organization=skarnes20
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
